# Generated by Django 2.0 on 2020-12-06 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='删除时间')),
                ('enable', models.BooleanField(default=1, verbose_name='有效')),
                ('user_id', models.CharField(max_length=50, verbose_name='用户uid')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户名称')),
                ('user_pwd', models.CharField(max_length=18, verbose_name='用户密码')),
                ('user_phone', models.CharField(max_length=11, verbose_name='用户手机')),
                ('user_email', models.CharField(max_length=20, verbose_name='用户邮箱')),
                ('real_name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('user_sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=1, verbose_name='性别')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': ('用户',),
                'db_table': 'user',
            },
        ),
    ]
